package EMS_Tests;

public class enumsClass {
	
	
	// Login types
	public enum loginData        { USERNAME, PASSWORD;}
		
	// Select types
	public enum selectTypes      { INDEX, NAME, GIVEN_TEXT;}
	
	// Browser types
	public enum browserTypes     { CHROME, FF, IE; }
	  
	// VOCA modes
	public enum vocaModes        { TLS, TCP, UDP;  }
	
	// Alarm filter modes
	public enum alarmFilterModes { DESCRPTION, SEVERITY, TENANT, INFO, REMOTE_HOST, SOURCE, NAME, ALARMS_AND_EVENTS, ALARMS_ONLY; }
	
	// Log modes
	public enum logModes {
		 	 
		MAJOR(""), NORMAL("   "), MINOR("      "), DEBUG("         ");  		 
		private String level = "";
		
		private logModes(String level) {		 
			this.level = level;   	 
		}
		public String getLevel() {   		 
			return level;    
		}
	 }
	
	// Menu names
	public enum menuNames {
		 	 
		MAINPAGE_DASHBOARD_ALARMS,
		MAINPAGE_GEN_INFOR_LOGOUT,
		MAINPAGE_MONITOR_GEN_INFOR_LOGOUT,
		MAINPAGE_MONITOR_GEN_INFOR_LOGOUT2,
		SETUP_SETUP_WIZARD,
		SETUP_MANAGE_USERS,
		SETUP_MANAGE_MULTIPE_USERS,
		SETUP_MANAGE_MULTIPE_DEVICES,		
		SETUP_PHONE_CONF_SECTION,
		SETUP_PHONE_CONF_TEMPLATES,
		SETUP_TEMPLATES_MAPPING,
		SETUP_PHONE_CONF_SYSTEM_SETTINGS,
		SETUP_PHONE_CONF_DHCP_OPTIONS_CONFIGURATION,
		SETUP_PHONE_CONF_SYSTEM_SETTINGS_SBC_CONF,
		SETUP_PHONE_CONF_SYSTEM_SETTINGS_SBC_LDAP,
		SETUP_PHONE_CONF_TEMPLATES_PLACEHOLDERS,
		SETUP_TENANT_CONFIGURATION,
		SETUP_SITE_CONFIGURATION,
		SETUP_USER_CONFIGURATION,
		SETUP_PHONE_CONFIGURATION_PHONE_DEVICE_PHS,
		SETUP_PHONE_CONFIGURATION_PHONE_CONF_FILES,
		SETUP_PHONE_CONFIGURATION_PHONE_FIRM_FILES,
		SETUP_IMPORT_EXPORT_CONFIGURATION_IMPORT,
		SETUP_IMPORT_EXPORT_CONFIGURATION_EXPORT,
		SETUP_IMPORT_EXPORT_USRS_DEVICES_IMPORT,
		SETUP_IMPORT_EXPORT_USRS_DEVICES_EXPORT,
		SETUP_SYSTEM_SECTION,
		SETUP_SYSTEM_VIEW_TENANTS,
		SETUP_SYSTEM_VIEW_SITES,
		SETUP_SYSTEM_LICENSE,
		MONITOR_DEVICE_STATUS,
		TROUBLESHOOT_SYSTEM_DIAGNOSTICS,
		TROUBLESHOOT_WEB_ADMIN_LOGS_MENU;
	}

	// Device Filter enums
	public enum deviceFilter {
		
		USER, PHONE_NUMBER, MAC_ADDRESS, IP_ADDRESS, VERSION, TENANT, SITE, TEMPLATE;
	}
}

